export const States = {
    LETTER_NOT_FOUND: "LETTER_NOT_FOUND",
    LETTER_UNKNOWN: "LETTER_UNKNOWN",
    LETTER_MATCHED: "LETTER_MATCHED",
    LETTER_ELSEWHERE: "LETTER_ELSEWHERE",
    UYIR_MATCHED: "UYIR_MATCHED",
    MEI_MATCHED: "MEI_MATCHED",
};
